swagger: '2.0'
info:
  version: 0.0.1
  title: payment
paths:
  
  
  /drinks:
    get:
      description: gets all drinks
      parameters:
        - name: after
          in: query
          description: createdDate
          required: false
          type: string
        - name: ingredients
          in: query
          description: array of possible ingredients
          type: array
          items:
            type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Drink'
    
  '/drinks/{drinkId}':
    get:
      description: gets one recipes
      parameters:
        - name: drinkId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Drink'
    
  '/users/{userId}':
    get:
      parameters:
        - in: path
          name: userId
          type: string
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
            
  /orders:
    post:
      produces:
          - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Order'
      responses:
        '201':
          description: Order succesfully placed
          headers:
            location:
              description: The Order ID
              type: string
  '/orders/{id}/state':
    get:
      produces:
        - text/plain
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: State available
          
definitions:
  Price:
    type: object
    properties:
      amount:
        type: number
        format: double
      currency:
        type: string
  
  Rating:
    type: object
    properties:
      value:
        type: number
      min:
        type: number
      max:
        type: number
      count:
        type: number
  User:
    type: object
    properties:
      id:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      thumbnail:
        type: string
        description: The Thumbnail jpg in base64
      imageRef:
        type: string
        description: The reference to the image
  Drink:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      description:
        type: string
      thumbnail:
        type: string
        format: byte
        description: The Thumbnail jpg in base64
      imageRef:
        type: string
        description: The reference to the image
      authorId:
        type: string
      createdAt:
        type: string
        format: date
      updatedAt:
        type: string
        format: date
      rating:
        $ref: '#/definitions/Rating'
      retailPrice:
        $ref: '#/definitions/Price'

  Order:
    type: object
    properties:
      recipeId:
        type: string
      customerName:
        type: string
      
        