/**
 * payment
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class User {
    id?: string;

    firstname?: string;

    lastname?: string;

    email?: string;

    /**
     * The Thumbnail jpg in base64
     */
    thumbnail?: string;

    /**
     * The reference to the image
     */
    imageRef?: string;

}
